# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='文章标题')),
                ('abstract', models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('time', models.DateField(verbose_name='编写时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('articlecomments', models.PositiveIntegerField(default=0, verbose_name='文章评论量')),
                ('articleimage', imagekit.models.fields.ProcessedImageField(blank=True, default='brand_img_pc_jocomomola-de-sybilla.jpg', upload_to='article', verbose_name='文章配图')),
                ('auther', models.CharField(default='劉汝翹', max_length=10, verbose_name='作者')),
            ],
            options={
                'verbose_name': '添加文章',
                'verbose_name_plural': '添加文章',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='评论者')),
                ('comment', models.CharField(max_length=300, verbose_name='评论内容')),
                ('userinfo', models.CharField(max_length=100, verbose_name='评论者的头像')),
                ('onclick', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('replaynum', models.PositiveIntegerField(default=0, verbose_name='回复量')),
                ('time', models.CharField(max_length=50, verbose_name='评论时间')),
                ('article', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Articles')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20, verbose_name='文章分类名')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='SubClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subusername', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subusername', models.CharField(max_length=20, verbose_name='回复者')),
                ('returneduser', models.CharField(max_length=20, verbose_name='被回复者')),
                ('subcomment', models.CharField(max_length=300, verbose_name='评论内容')),
                ('subuserinfo', models.CharField(max_length=100, verbose_name='回复者头像')),
                ('onclick', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('time', models.CharField(max_length=50, verbose_name='回复时间')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签名')),
            ],
            options={
                'verbose_name': '标签云',
                'verbose_name_plural': '标签云',
            },
        ),
        migrations.CreateModel(
            name='SecondComment',
            fields=[
                ('subcomment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.SubComment')),
            ],
            bases=('blog.subcomment',),
        ),
        migrations.AddField(
            model_name='subcomment',
            name='fathercomment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AddField(
            model_name='subclick',
            name='target',
            field=models.ManyToManyField(blank=True, to='blog.SubComment'),
        ),
        migrations.AddField(
            model_name='click',
            name='target',
            field=models.ManyToManyField(blank=True, to='blog.Comment'),
        ),
        migrations.AddField(
            model_name='articles',
            name='goupname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Group', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='标签集合'),
        ),
        migrations.AddField(
            model_name='secondcomment',
            name='second_father_comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='second_comment', to='blog.SubComment'),
        ),
    ]
